name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_roadmap
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Build backend Docker image
        run: docker build -t roadmap-backend ./backend
      - name: Run backend tests
        run: >
          docker run --rm
          --network host
          -e DB_HOST=localhost
          roadmap-backend pytest tests/ --import-mode=importlib

  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build frontend Docker image
        run: docker build -t roadmap-frontend ./frontend
      - name: Run frontend tests
        run: docker run --rm -e CI=true roadmap-frontend sh -c "npm ci && npm test"
  report-status:
    needs: [build-test-backend, build-test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Report CI status
        run: echo "CI build and test completed."
