name: "Docs Check"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for docs update confirmation
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body;
            if (!/\[x\] I have updated the architecture documentation/.test(body)) {
              core.setFailed("Please confirm that you have updated the architecture documentation by checking the box in the PR description.");
            }
          github-token: ${{secrets.GITHUB_TOKEN}}
